backend:
  name: github
  repo: nomad-house/nomad.house
  branch: master
  site_domain: codeified.org
  base_url: https://nomad-devops.nomad.house/v1
  auth_endpoint: auth
local_backend: true
publish_mode: editorial_workflow
media_folder: 'static/media'
public_folder: 'static/media'
site_url: https://nomad.house
collections:
  - name: authors
    label: Authors
    folder: assets/content/authors
    create: true
    slug: '{{slug}}'
    identified_field: name
    fields:
      - name: name
        label: Name
        widget: string
        required: true
      - name: description
        label: Description
        widget: markdown
        required: false
        hint: The authors bio
  - name: categories
    label: Categories
    label_singular: Category
    folder: assets/content/categories
    create: true
    slug: '{{slug}}'
    identified_field: name
    fields:
      - name: name
        label: Name
        widget: string
        required: true
      - name: description
        label: Description
        widget: markdown
        required: false
        hint: A bit about the category
  - name: tags
    label: Tags
    folder: assets/content/tags
    create: true
    slug: '{{slug}}'
    identified_field: name
    fields:
      - name: name
        label: Name
        widget: string
        required: true
      - name: description
        label: Description
        widget: markdown
        required: false
        hint: A bit about the tag
  - name: recipes
    label: Recipes
    folder: assets/content/recipes
    create: true
    preview_path: '{{slug}}'
    slug: '{{slug}}'
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: subtitle
        label: Subtitle
        widget: string
        required: false
      - name: hero
        lable: Hero Image
        widget: image
        require: true
      - name: author
        label: Author
        widget: relation
        required: true
        collection: authors
        valueField: name
        searchFields: [name]
        displayFields: [name]
      - name: tags
        label: Tags
        widget: relation
        multiple: true
        required: false
        collection: tags
        valueField: name
        searchFields: [name]
        displayFields: [name]
      - name: published
        label: Publish Date
        widget: datetime
        default: true
        required: true
      - name: updated
        label: Updated Date
        widget: datetime
        default: ''
        required: false
      - name: description
        label: Description
        widget: text
        required: false
      - name: ingredients
        label: Ingredients
        widget: list
        required: true
        allow_add: true
        minimize_collapsed: true
        summary: '{{fields.name}}, {{fields.preparation}} {{fields.options}}'
        fields:
          - name: quantities
            label: Quantities
            label_singular: Quantity
            widget: list
            required: true
            collapsed: false
            summary: '{{fields.quantity}} {{fields.label}}'
            fields:
              - name: quantity
                label: Quantity
                required: true
                widget: number
                valueType: float
                min: 0
              - name: label
                label: Quantity Label
                widget: select
                required: false
                options:
                  [
                    'tsp',
                    'tbsp',
                    'cup',
                    'pint',
                    'quart',
                    'gallon',
                    'ounce',
                    'pound',
                    'mg',
                    'g',
                    'kg',
                    'ml',
                    'l',
                    'in',
                    'ft',
                    'cm',
                    'm',
                    'piece',
                    'slice',
                    'can',
                    'bag',
                  ]
          - name: mass
            label: Mass Equivalent
            widget: object
            required: false
            collapsed: true
            summary: '{{fields.quantity}} {{fields.label}}'
            fields:
              - name: quantity
                label: Quantity
                widget: number
                valueType: float
                min: 0
                required: true
              - name: label
                label: Quantity Label
                widget: select
                required: false
                options: ['ounce', 'pound', 'mg', 'g', 'kg']
          - name: name
            label: Name
            widget: string
            required: true
          - name: preparation
            label: Preparation
            widget: string
            required: false
          - name: options
            label: Options
            widget: select
            required: false
            options: ['optional']
      - name: instructions
        label: Instructions
        widget: list
        required: true
        allow_add: true
        minimize_collapsed: true
        summary: '{{fields.description}}'
        field: { name: description, label: Description, widget: text }
  - name: posts
    label: Posts
    folder: assets/content/posts
    create: true
    preview_path: '{{slug}}'
    slug: '{{slug}}'
    fields:
      - { name: title, label: Title, widget: string, required: true }
      - { name: subtitle, label: Subtitle, widget: string, required: false }
      - { name: hero, lable: Hero Image, widget: image, require: true }
      - {
          name: author,
          label: Author,
          widget: relation,
          required: true,
          collection: authors,
          valueField: slug,
          searchFields: [name],
          displayFields: [name],
        }
      - {
          name: category,
          label: Category,
          widget: relation,
          multiple: true,
          collection: categories,
          valueField: name,
          searchFields: [name],
          displayFields: [name],
        }
      - {
          name: published,
          label: Publish Date,
          widget: datetime,
          default: true,
          required: true,
        }
      - {
          name: updated,
          label: Updated Date,
          widget: datetime,
          default: true,
          required: false,
        }
      - {
          name: prominent,
          label: Prominent,
          widget: boolean,
          default: false,
          required: false,
        }
      - { name: body, label: Body, widget: markdown, required: true }
